language: node_js
node_js:
  - "stable"
  - "4.1"
  - "4"
  - "0.12"
  - "0.10"
script:
  - npm run lint
  - npm test
  - npm run integration-test
after_success:
  - '[ -z "$COVERALLS_REPO_TOKEN" ] && npm run coveralls'
